CREATE TABLE client (
    id_client NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Clé primaire auto-générée
    nom_client VARCHAR2(255) NOT NULL,    -- Nom du client (obligatoire)
    adresse VARCHAR2(500),                -- Adresse du client
    pays VARCHAR2(100),                   -- Pays du client
    telephone VARCHAR2(20),               -- Numéro de téléphone
    vendeur VARCHAR2(255),                -- Nom du vendeur associé au client
    region VARCHAR2(255)                  -- Région du client
);

CREATE TABLE produit (
    id_produit NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Clé primaire auto-générée
    nom VARCHAR2(150) NOT NULL,      -- Nom du produit
    prix NUMBER(10, 2) NOT NULL,     -- Prix du produit avec deux décimales
    cout NUMBER(10, 2) NOT NULL,     -- Coût du produit avec deux décimales
    stock NUMBER DEFAULT 0,          -- Quantité en stock avec une valeur par défaut de 0
    date_cree DATE DEFAULT SYSDATE,  -- Date de création avec une valeur par défaut de la date actuelle
    categorie NUMBER                 -- Catégorie du produit (référence à une autre table, par exemple)
);

CREATE TABLE utilisateur (
    id_utilisateur NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Clé primaire auto-générée
    nom VARCHAR2(100) NOT NULL,        -- Nom de l'utilisateur
    prenom VARCHAR2(100) NOT NULL,     -- Prénom de l'utilisateur
    adresse VARCHAR2(255),             -- Adresse de l'utilisateur
    ville VARCHAR2(100),               -- Ville de l'utilisateur
    courriel VARCHAR2(255) NOT NULL UNIQUE, -- Courriel de l'utilisateur, doit être unique
    mdp VARCHAR2(255) NOT NULL         -- Mot de passe de l'utilisateur
);

CREATE TABLE panier (
    id_panier NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Clé primaire auto-générée
    id_client NUMBER NOT NULL,          -- Clé étrangère pour client
    date_creation DATE DEFAULT SYSDATE, -- Date de création avec valeur par défaut à la date actuelle
    id_utilisateur NUMBER NOT NULL,     -- Clé étrangère pour utilisateur
    note VARCHAR2(255),                 -- Note pour la panier
    CONSTRAINT fk_client FOREIGN KEY (id_client) REFERENCES client(id_client),
    CONSTRAINT fk_utilisateur FOREIGN KEY (id_utilisateur) REFERENCES utilisateur(id_utilisateur)
);

CREATE TABLE item (
    id_item NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Clé primaire auto-générée
    id_panier NUMBER NOT NULL,       -- Clé étrangère vers la table panier
    id_produit NUMBER NOT NULL,      -- Clé étrangère vers la table produit
    qte_commande NUMBER NOT NULL,    -- Quantité commandée
    prix NUMBER(10, 2) NOT NULL,     -- Prix du produit au moment de la commande
    escompte NUMBER(5, 2) DEFAULT 0, -- Escompte (pourcentage de réduction), valeur par défaut 0
    CONSTRAINT fk_panier FOREIGN KEY (id_panier) REFERENCES panier(id_panier),
    CONSTRAINT fk_produit FOREIGN KEY (id_produit) REFERENCES produit(id_produit)
);

-- peuplement des tables
--client
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Jean Tremblay', '1234 Rue Sainte-Catherine, Montréal', 'Canada', '514-555-0101', null, 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Lucie Lefebvre', '987 Boulevard René-Lévesque, Québec', 'Canada', '418-555-0102', 'Vendeur B', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Marie Boucher', '1234 Avenue Laurier, Montréal', 'Canada', '514-555-0103', 'Vendeur A', 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Pierre Gagnon', '4321 Rue Saint-Denis, Montréal', 'Canada', '514-555-0104', 'Vendeur C', 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Caroline Tremblay', '5678 Rue Saint-Jean, Québec', 'Canada', '418-555-0105', null, 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Jacques Roy', '1122 Boulevard Saint-Laurent, Montréal', 'Canada', '514-555-0106', 'Vendeur A', 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Sophie Morin', '5555 Chemin Sainte-Foy, Québec', 'Canada', '418-555-0107', 'Vendeur C', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Marc-André Fortin', '7890 Rue Sherbrooke, Montréal', 'Canada', '514-555-0108', null, 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Julie Pelletier', '1234 Boulevard de Maisonneuve, Québec', 'Canada', '418-555-0109', 'Vendeur A', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Martin Desjardins', '1111 Rue Ontario, Montréal', 'Canada', '514-555-0110', 'Vendeur C', 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Pauline Charbonneau', '22 Rue de la Montagne, Québec', 'Canada', '418-555-0111', 'Vendeur A', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Bruno Landry', '10 Rue Royale, Montréal', 'Canada', '514-555-0112', 'Vendeur B', 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Dominique Parent', '333 Rue Saint-Paul, Québec', 'Canada', '418-555-0113', 'Vendeur C', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Denis Lavoie', '88 Avenue Cartier, Montréal', 'Canada', '514-555-0114', null, 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Catherine Gauthier', '5 Rue de la Cité, Québec', 'Canada', '418-555-0115', 'Vendeur B', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Patrick Lefrançois', '12 Rue du Lac, Montréal', 'Canada', '514-555-0116', 'Vendeur C', 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Sandrine Dufresne', '45 Rue du Nord, Québec', 'Canada', '418-555-0117', 'Vendeur A', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Yannick Gagné', '123 Rue Frontenac, Québec', 'Canada', '418-555-0118', 'Vendeur B', 'Québec');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Geneviève Larose', '90 Rue des Pins, Montréal', 'Canada', '514-555-0119', 'Vendeur C', 'Montréal');
INSERT INTO client (nom_client, adresse, pays, telephone, vendeur, region) VALUES ('Louis Martel', '78 Rue Saint-Jean, Québec', 'Canada', '418-555-0120', null, 'Québec');
--produit
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Laptop Dell Inspiron', 899.99, 700.00, 10, 1);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Ordinateur Portable HP', 749.99, 600.00, 15, 1);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Écran 24 pouces Samsung', 199.99, 150.00, null, 2);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Clavier Logitech', 49.99, 30.00, 100, 3);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Souris Sans Fil Microsoft', 29.99, 20.00, 50, 3);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Disque Dur Externe 1TB', 79.99, 60.00, 25, 4);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Carte Graphique Nvidia GTX 1650', 299.99, 250.00, null, 5);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Imprimante Canon', 129.99, 100.00, 8, 6);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Casque Audio Bose', 199.99, 150.00, 30, 3);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Câble HDMI', 19.99, 10.00, 200, 7);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Tablette Samsung Galaxy', 349.99, 300.00, null, 1);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Clé USB 64GB', 14.99, 10.00, 150, 4);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Chaise de Bureau Ergonomique', 199.99, 120.00, 50, 6);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Support Moniteur', 29.99, 20.00, 100, 7);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Station d’Accueil Lenovo', 149.99, 100.00, 40, 5);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Routeur WiFi Netgear', 99.99, 70.00, null, 4);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Enceinte Bluetooth JBL', 59.99, 40.00, 60, 3);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Lampe LED de Bureau', 39.99, 25.00, 80, 6);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Webcam HD Logitech', 89.99, 60.00, null, 5);
INSERT INTO produit (nom, prix, cout, stock, categorie) VALUES ('Scanner Epson', 129.99, 100.00, 15, 6);
--utilisateur
INSERT INTO utilisateur (nom, prenom, adresse, ville, courriel, mdp) VALUES ('Dupont', 'Alain', '1234 Rue des Ormes', 'Montréal', 'alain.dupont@example.com', 'password123');
INSERT INTO utilisateur (nom, prenom, adresse, ville, courriel, mdp) VALUES ('Martin', 'Isabelle', '5678 Rue des Pins', 'Québec', 'isabelle.martin@example.com', 'password456');
INSERT INTO utilisateur (nom, prenom, adresse, ville, courriel, mdp) VALUES ('Roy', 'Sophie', '91011 Rue Papineau', 'Montréal', 'sophie.roy@example.com', 'password789');
--commande
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (1, 1, 'Commande pour ordinateur et accessoires', to_date('2024-12-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (2, 2, 'Commande urgente pour client fidèle', to_date('2024-12-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (3, 3, 'Commande de Noël pour client important', to_date('2024-12-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (4, 1, 'Commande pour nouvelle entreprise', to_date('2024-12-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (5, 2, 'Commande pour mise à jour matérielle', to_date('2025-01-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (6, 3, 'Commande spéciale pour projet scolaire', to_date('2025-01-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (7, 1, 'Commande avec livraison express', to_date('2025-01-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (8, 2, 'Commande pour un nouvel employé', to_date('2025-01-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (9, 3, 'Commande de remplacement d''équipement', to_date('2025-01-01','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (10, 1, 'Commande pour un nouveau client', to_date('2025-01-21','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (11, 1, 'Commande entreprise Pauline Charbonneau', to_date('2025-01-21','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (12, 2, 'Commande de Bruno Landry pour bureau', to_date('2025-01-21','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (13, 3, 'Commande Dominique Parent pour projet', to_date('2025-01-21','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (14, 1, 'Commande Denis Lavoie pour Noël', to_date('2025-01-21','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (15, 2, 'Commande de Catherine Gauthier pour entreprise', to_date('2025-01-21','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (16, 3, 'Commande Patrick Lefrançois pour stock', to_date('2025-01-21','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (17, 1, 'Commande Sandrine Dufresne pour usage personnel', to_date('2025-01-28','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (18, 2, 'Commande Yannick Gagné pour équipement audio', to_date('2025-01-29','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (19, 3, 'Commande Geneviève Larose pour webcam et accessoires', to_date('2025-01-29','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (20, 1, 'Commande Louis Martel pour entreprise informatique', to_date('2025-01-29','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (1, 1, 'Commande supplémentaire pour Jean Tremblay - accessoires pour ordinateur', to_date('2025-01-29','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (2, 2, 'Commande pour Lucie Lefebvre - équipement de bureau', to_date('2025-01-29','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (5, 3, 'Commande supplémentaire pour Caroline Tremblay - produits informatiques', to_date('2025-01-29','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (9, 2, 'Commande supplémentaire pour Julie Pelletier - mise à jour matérielle', to_date('2025-02-04','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (10, 3, 'Commande pour Martin Desjardins - remplacement de matériel', to_date('2025-02-04','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (10, 3, 'Deuxième commande pour Martin Desjardins - périphériques supplémentaires', to_date('2025-02-04','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (10, 3, 'Troisième commande pour Martin Desjardins - accessoires bureautiques', to_date('2025-02-04','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (13, 2, 'Commande supplémentaire pour Dominique Parent - composants informatiques', to_date('2025-02-04','YYYY-MM-DD'));
INSERT INTO panier (id_client, id_utilisateur, note, date_creation) VALUES (13, 2, 'Deuxième commande pour Dominique Parent - mise à jour de matériel', to_date('2025-02-04','YYYY-MM-DD'));

--insertion des détails de commande
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (1, 1, 1, 899.99, 5.00);  -- Laptop Dell Inspiron avec 5% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (1, 2, 1, 749.99, null);    -- Ordinateur Portable HP sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (2, 3, 2, 199.99, 10.00);-- Écran Samsung avec 10% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (2, 4, 5, 49.99,null);     -- Clavier Logitech sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (3, 5, 3, 29.99, 5.00);  -- Souris Sans Fil avec 5% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (1, 1, 1, 899.99, 5.00);   -- Laptop Dell Inspiron avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (1, 2, 1, 749.99,null);     -- Ordinateur Portable HP sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (2, 3, 2, 199.99, 10.00); -- Écran Samsung avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (2, 4, 5, 49.99,null);      -- Clavier Logitech sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (3, 5, 3, 29.99, 5.00);   -- Souris sans fil avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (3, 6, 1, 79.99,null);      -- Disque dur externe sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (4, 7, 1, 299.99,null);     -- Carte Graphique Nvidia sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (4, 8, 2, 129.99, 5.00);  -- Imprimante Canon avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (5, 9, 1, 199.99,null);     -- Casque audio Bose sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (5, 10, 3, 19.99,null);     -- Câble HDMI sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (6, 1, 1, 899.99, 5.00);  -- Laptop Dell Inspiron avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (6, 3, 2, 199.99, 10.00); -- Écran Samsung avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (7, 4, 5, 49.99,null);      -- Clavier Logitech sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (7, 6, 1, 79.99,null);      -- Disque dur externe sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (8, 7, 1, 299.99,null);     -- Carte Graphique Nvidia sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (8, 8, 1, 129.99, 5.00);  -- Imprimante Canon avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (9, 9, 2, 199.99,null);     -- Casque audio Bose sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (9, 5, 4, 29.99,null);      -- Souris sans fil sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (10, 10, 5, 19.99,null);    -- Câble HDMI sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (10, 1, 1, 899.99, 5.00); -- Laptop Dell Inspiron avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (11, 11, 1, 349.99, 5.00); -- Tablette Samsung Galaxy avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (11, 12, 10, 14.99,null);    -- Clé USB 64GB sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (12, 13, 2, 199.99, 10.00); -- Chaise de bureau avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (12, 14, 3, 29.99,null);      -- Support moniteur sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (13, 15, 1, 149.99, 5.00);  -- Station d'accueil Lenovo avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (13, 16, 2, 99.99,null);      -- Routeur WiFi sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (14, 17, 1, 59.99,null);      -- Enceinte Bluetooth sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (14, 18, 2, 39.99,null);      -- Lampe LED sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (15, 19, 1, 89.99, 5.00);   -- Webcam HD Logitech avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (15, 20, 1, 129.99, 10.00); -- Scanner Epson avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (16, 1, 1, 899.99, 5.00);   -- Laptop Dell Inspiron avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (16, 2, 1, 749.99,null);      -- Ordinateur Portable HP sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (17, 3, 2, 199.99, 10.00);  -- Écran Samsung avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (17, 4, 3, 49.99,null);       -- Clavier Logitech sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (18, 5, 1, 29.99, 5.00);    -- Souris sans fil avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (18, 6, 2, 79.99,null);       -- Disque dur externe sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (19, 7, 1, 299.99,null);      -- Carte graphique Nvidia sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (19, 8, 1, 129.99, 5.00);   -- Imprimante Canon avec réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (20, 9, 1, 199.99,null);      -- Casque audio Bose sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (20, 10, 5, 19.99,null);      -- Câble HDMI sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (21, 4, 3, 49.99,null);  -- Clavier Logitech
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (21, 5, 2, 29.99, 5.00);  -- Souris sans fil avec 5% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (22, 7, 1, 299.99, 10.00);  -- Carte graphique Nvidia GTX 1650 avec 10% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (22, 9, 1, 199.99,null);  -- Casque audio Bose sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (23, 1, 1, 899.99, 5.00);  -- Laptop Dell Inspiron avec 5% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (23, 8, 2, 129.99,null);  -- Imprimante Canon sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (24, 2, 1, 749.99,null);  -- Ordinateur Portable HP sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (24, 6, 2, 79.99,null);  -- Disque dur externe 1TB sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (25, 10, 5, 19.99,null);  -- Câble HDMI sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (25, 3, 1, 199.99,null);  -- Écran 24 pouces Samsung sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (26, 4, 2, 49.99,null);  -- Clavier Logitech sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (26, 5, 1, 29.99, 5.00);  -- Souris sans fil avec 5% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (27, 3, 1, 199.99,null);  -- Écran 24 pouces Samsung sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (27, 7, 1, 299.99, 10.00);  -- Carte graphique Nvidia GTX 1650 avec 10% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (28, 6, 1, 79.99,null);  -- Disque dur externe sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (28, 8, 1, 129.99,null);  -- Imprimante Canon sans réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (29, 1, 1, 899.99, 5.00);  -- Laptop Dell Inspiron avec 5% de réduction
INSERT INTO item (id_panier, id_produit, qte_commande, prix, escompte) VALUES (29, 9, 1, 199.99,null);  -- Casque audio Bose sans réduction
commit;